### ISSUE TITLE
Deprecation Issue & 1 Other Major Issue: Cannot find anything online in regards to this

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#163]
(node:3773) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
[1] (Use `node --trace-deprecation ...` to show where the warning was created)

When I use command, it gives me this:

Error: Cannot find module '/Users/carlitos/creativeduoshopping-master/...'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Also, I killall node and it gave me this still: 

node:events:371
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: listen EADDRINUSE: address already in use :::5000
[0]     at Server.setupListenHandle [as _listen2] (node:net:1305:16)
[0]     at listenInCluster (node:net:1353:12)
[0]     at Server.listen (node:net:1440:7)
[0]     at Function.listen (/Users/carlitos/creativeduoshopping-master/node_modules/express/lib/application.js:618:24)
[0]     at file:///Users/carlitos/creativeduoshopping-master/backend/server.js:93:5
[0]     at ModuleJob.run (node:internal/modules/esm/module_job:175:25)
[0]     at async Loader.import (node:internal/modules/esm/loader:178:24)
[0]     at async Object.loadESM (node:internal/process/esm_loader:68:5)
[0]     at async handleMainPromise (node:internal/modules/run_main:63:12)
[0] Emitted 'error' event on Server instance at:
[0]     at emitErrorNT (node:net:1332:8)
[0]     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
[0]   code: 'EADDRINUSE',
[0]   errno: -48,
[0]   syscall: 'listen',
[0]   address: '::',
[0]   port: 5000
[0] }

@basir @bradtraversy

**Comment by alexakarpov** [comment]
it appears this issue is _not_ with this repo, but with your work on the related course. Reading the error message, it looks like your problem is that port 5000 is already in use - so you can't listen on it. Reading error messages is an acquired skill, I know )

**Comment by basir** [comment]
I answered this issue on the Udemy.
