### ISSUE TITLE
Quick Erro

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#64]
Hi, I know this is supposed to be for bugs but here is a problem i am having:

[0] events.js:291
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: listen EADDRINUSE: address already in use :::5000
[0]     at Server.setupListenHandle [as _listen2] (net.js:1317:16)
[0]     at listenInCluster (net.js:1365:12)
[0]     at Server.listen (net.js:1451:7)
[0]     at Function.listen (/Users/carlosdiazplaza/Documents/Creative-Duo-Shop/node_modules/express/lib/application.js:618:24)
[0]     at file:///Users/carlosdiazplaza/Documents/Creative-Duo-Shop/backend/server.js:55:5
[0]     at ModuleJob.run (internal/modules/esm/module_job.js:146:23)
[0]     at async Loader.import (internal/modules/esm/loader.js:165:24)
[0]     at async Object.loadESM (internal/process/esm_loader.js:68:5)
[0] Emitted 'error' event on Server instance at:
[0]     at emitErrorNT (net.js:1344:8)
[0]     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
[0]   code: 'EADDRINUSE',
[0]   errno: -48,
[0]   syscall: 'listen',
[0]   address: '::',
[0]   port: 5000
[0] }
[0] [nodemon] app crashed - waiting for file changes before starting...
[1] ℹ ｢wds｣: Project is running at http://192.168.1.66/
[1] ℹ ｢wds｣: webpack output is served from 
[1] ℹ ｢wds｣: Content not from webpack is served from /Users/carlosdiazplaza/Documents/Creative-Duo-Shop/frontend/public
[1] ℹ ｢wds｣: 404s will fallback to /
[1] Starting the development server...

Any help?

**Comment by aorelhas** [comment]
This error is due to you have an instance running on PORT 5000.

This is how you can solve this:

In your terminal type:
lsof -i tcp:5000

After you see the PID running
kill -9 PID

But anyway, you should search for this type of error on Google. It's a common error.

**Comment by bradtraversy** [comment]
Please search google for this type of thing
