### ISSUE TITLE
ReferenceError: Cannot access 'products' before initialization

### ISSUE THREAD

**Issue by nikhilsiem** [bradtraversy/proshop_mern#81]
When I installed 'express-aync-handler' and changed the code for productsRoute.js(ie after the video- fetching products from database) I am not getting the products on localhost:5000/api/products. rather I am getting the following-

ReferenceError: Cannot access 'products' before initialization
    at file:///C:/Users/Administrator/storyteller/backend/routes/productRoutes.js:11:22
    at asyncUtilWrap (C:\Users\Administrator\storyteller\node_modules\express-async-handler\index.js:3:20)
    at Layer.handle [as handle_request] (C:\Users\Administrator\storyteller\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Administrator\storyteller\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Administrator\storyteller\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Administrator\storyteller\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Administrator\storyteller\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Administrator\storyteller\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Administrator\storyteller\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\Administrator\storyteller\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\Administrator\storyteller\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\Administrator\storyteller\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Administrator\storyteller\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Administrator\storyteller\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Administrator\storyteller\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Administrator\storyteller\node_modules\express\lib\router\index.js:275:10)

What probably couldve gone wrong?  @basir @bradtraversy

**Comment by nikhilsiem** [comment]
Its solved. My bad guys.
