### ISSUE TITLE
How can I get this to not happen?

### ISSUE THREAD

**Issue by talmax1124** [bradtraversy/proshop_mern#92]
Hi, I have tried to deploy to heroku and it is saying this

internal/modules/cjs/loader.js:311
      throw err;
      ^
Error: Cannot find module '/tmp/build_211f302b_/frontend/node_modules/semver/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/build_211f302b_/frontend/node_modules/react-scripts/scripts/utils/verifyPackageTree.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/tmp/build_211f302b_/frontend/node_modules/semver/package.json',
  requestPath: 'semver'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.zjXOR/_logs/2021-01-11T13_00_22_701Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! creative-duo-shop@1.0.0 heroku-postbuild: `NPM_CONFIG_PRODUCTION=false npm install --prefix frontend && npm run build --prefix frontend`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the creative-duo-shop@1.0.0 heroku-postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /tmp/npmcache.zjXOR/_logs/2021-01-11T13_00_22_732Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - node_modules checked into source control
         https://devcenter.heroku.com/articles/node-best-practices#only-git-the-important-bits
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

The thing is that I don't have something called semver at all. I have searched all of the links and docs and there is nothing I can do to fix it. & since I have a free plan, I can't email them. Can anyone help. You can find my repo by going to my repo and look for talmax1124/shop

**Comment by talmax1124** [comment]
@basir @bradtraversy

**Comment by talmax1124** [comment]
Can anyone help?

**Comment by talmax1124** [comment]
@basir @bradtraversy Anyone?
